# Pytorch
 - Define-by-Run

# Pytorch Packages

 - **torch**
 - torch.autograd
 - torch.nn
 - torch.optim
 - torch.multiprocessing
 - torch.utils
 - torch.legact

# Pytorch Tensor Basic Usage

- Create Tensor
- Indexing, Joining, Slicing
- Initialization
- Math Operations

## 1. Create Tensor

### 1) random numbers

In [2]:
from __future__ import print_function
import torch

In [29]:
# torch.rand(size)
# 0~1 사이의 연속균등분포에서 값을 뽑아 5x3 텐서를 생성합니다. ~U(0,1)
x = torch.rand(2,3)
x

tensor([[0.7737, 0.6550, 0.2810],
        [0.7215, 0.2243, 0.4761]])

In [30]:
# torch.randn(size)
# randn의 경우 평균은 0, 표준편차는 1인 정규분포에서 값을 가져옵니다. ~z(0,1)
x = torch.randn(2,3)
x

tensor([[ 0.8413, -0.1285,  1.1922],
        [ 1.9749,  0.1730,  2.0156]])

In [31]:
# torch.randperm(n)
# 0부터 n-1까지 1씩 늘어나며 값을 랜덤으로 정렬합니다.
x = torch.randperm(5)
x

tensor([2, 1, 3, 4, 0])

### 2) empty, zeros, ones, arange, max

In [32]:
# torch.empty(size)
# 원하는 크기의 빈 텐서를 생성합니다.
x = torch.empty(2,3)
x

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [33]:
# torch.zeros(size)
# 원하는 크기의 빈 텐서를 생성합니다.
x = torch.zeros(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [34]:
# torch.ones(size)
# 원하는 크기의 1의 값을 가진 텐서를 생성합니다.
x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [35]:
# torch.arange(start,end,step=1)
# start값부터 end값 전까지 step만큼 더하며 텐서를 생성합니다.
x = torch.arange(0,3,step=0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

In [11]:
# torch.max(input, dim, keepdim=False, out=None) -> (Tensor, LongTensor)
# tensor의 최대값을 산출합니다.

x = torch.rand(2,3)
print(x)

# 최대값을 출력합니다.
print(torch.max(x))

# 해당 차원에서 최대값과 그 위치를 출력합니다.
print(torch.max(x,1))

# 위치를 출력합니다.
print(torch.max(x,1)[1])

tensor([[0.0811, 0.8639, 0.8585],
        [0.4495, 0.9369, 0.6960]])
tensor(0.9369)
(tensor([0.4495, 0.9369, 0.8585]), tensor([1, 1, 0]))
tensor([1, 1])


### 3) Tensor Data Type

| Data type               | dtype                                         | Tensor types                 |
|:-------------------------|:-----------------------------------------------|:------------------------------|
| 32-bit floating point   | ``` torch.float32 ``` or ``` torch.float ```  | ``` torch.*.FloatTensor ```  |
| 64-bit floating point   | ``` torch.float64 ``` or ``` torch.double ``` | ``` torch.*.DoubleTensor ``` |
| 16-bit floating point   | ``` torch.float16 ``` or ``` torch.half ```   | ``` torch.*.HalfTensor ```   |
| 16-bit integer (signed) | ``` torch.int16 ``` or ``` torch.short ```    | ``` torch.*.ShortTensor ```  |
| 32-bit integer (signed) | ``` torch.int32 ``` or ``` torch.int ```      | ``` torch.*.IntTensor ```    |
| 64-bit integer (signed) | ``` torch.int64 ``` or ``` torch.long ```     | ``` torch.*.LongTensor ```   |

In [38]:
# torch.empty(size, dtype=)
# torch.zeros(size, dtype=)
# torch.arange(start,end,dtype=)

# torch에서 지원하는 다양한 data type을 옵션으로 지정할 수 있습니다.

x = torch.empty(2,3, dtype=torch.float)
y = torch.zeros(2,3, dtype = torch.long)
z = torch.arange(0,3,step=0.5,dtype=torch.double)

print(x)
print(y)
print(z)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000], dtype=torch.float64)


In [40]:
# torch.tensor(size or list, dtype = torch.floattensor) 
# 원하는 텐서를 바로 생성합니다.
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [42]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor(2,3)
print(x)
x = torch.FloatTensor([2,3])
print(x)

tensor([[-0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])
tensor([2., 3.])


In [43]:
# tensor.type_as(tensor_type)
# tensor 형 변환
x = x.type_as(torch.IntTensor())
x

tensor([2, 3], dtype=torch.int32)

### 4) Tensor Size

In [48]:
# tensor.size()

x = torch.FloatTensor(10,12,3,3)

print(x.size()[:])
print(x.size()[0])

torch.Size([10, 12, 3, 3])
10


In [40]:
x = x.new_ones(5,3, dtype=torch.double) #5,3 차원의 새로운 텐서를 생성합니다.
print(x)

x = torch.randn_like(x,dtype=torch.float) # 같은 size에서 랜덤한 숫자로 채워진 텐서를 생성합니다.
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.5949,  0.3606, -0.0697],
        [-0.2124, -0.9243,  1.5786],
        [ 1.2222,  2.4934,  0.2329],
        [-0.6524, -0.3773,  0.1990],
        [ 0.1745, -0.0725, -1.3324]])


## 2. Math Operations

### 1) add, mul, div

In [50]:
# torch.add()
# 텐서의 값끼리 더합니다.

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
add = torch.add(x1, x2)

x1,x2,add,x1+x2,x1-x2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]), tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]), tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [59]:
# out option은 결과로 받을 텐서를 지정합니다.
# 없으면 알아서 만들어냅니다.

torch.add(x1,x2,out=result) 
print(result)

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [43]:
#차원이 다르더라도 안쪽 차원만 같으면 연산이 가능합니다.

x = torch.rand(1,5,3)
y = torch.rand(5,3)
torch.add(x,y)

tensor([[[0.6673, 0.6532, 0.8410],
         [0.9674, 1.7119, 0.4976],
         [0.9666, 1.5755, 0.9870],
         [0.8471, 0.3932, 1.5169],
         [0.2085, 1.1244, 1.7623]]])

In [45]:
# torch.add 말고 add_의 경우에는 이러한 연산 기능이 지원되지 않습니다. 따라서 먼저 x를 같은 차원으로 바꿔줍니다.

x = torch.rand(5,3)
y.add_(x)
print(y)

tensor([[0.6340, 0.9185, 0.7175],
        [0.4609, 1.1804, 0.1689],
        [0.5956, 0.6734, 1.1183],
        [1.4676, 0.5494, 0.9229],
        [0.4351, 1.3508, 1.1279]])


In [60]:
# x 텐서의 2열을 불러옵니다. numpy 연산이 지원됩니다.

print(x)
print(x[:,1])

tensor([[[[ 0.0000e+00,  0.0000e+00,  1.0402e+22],
          [ 0.0000e+00,  5.7397e-42,  0.0000e+00],
          [        nan,         nan, -4.0565e+31]],

         [[ 5.6192e-43, -5.9708e+31,  5.6192e-43],
          [-5.9709e+31,  5.6192e-43, -5.9710e+31],
          [ 5.6192e-43, -5.9710e+31,  5.6192e-43]],

         [[-5.9710e+31,  5.6192e-43, -5.9708e+31],
          [ 5.6192e-43, -5.9711e+31,  5.6192e-43],
          [-5.9712e+31,  5.6192e-43, -5.9712e+31]],

         ...,

         [[ 5.6192e-43, -6.0496e+31,  5.6192e-43],
          [-6.0497e+31,  5.6192e-43, -6.0497e+31],
          [ 5.6192e-43, -6.0497e+31,  5.6192e-43]],

         [[-6.0498e+31,  5.6192e-43, -6.0498e+31],
          [ 5.6192e-43, -6.0498e+31,  5.6192e-43],
          [-6.0499e+31,  5.6192e-43, -6.0500e+31]],

         [[ 5.6192e-43, -6.0500e+31,  5.6192e-43],
          [-6.0500e+31,  5.6192e-43, -6.0501e+31],
          [ 5.6192e-43, -6.0501e+31,  5.6192e-43]]],


        [[[-6.0501e+31,  5.6192e-43, -6.0502e+31],
  

In [65]:
# torch.mul()
# hadamard product, mxn, mxn 행렬 2개를 곱합니다. 덧셈에 대해 분배법칙을 따릅니다.

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.mul(x1,x2)

x3, x3.size()

(tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]), torch.Size([2, 3]))

In [67]:
# torch.mul()

x1 = torch.FloatTensor([[1,2,3,],[4,5,6]])
x2 = x1*10

x2

tensor([[10., 20., 30.],
        [40., 50., 60.]])

In [68]:
# torch.div()

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.div(x1,x2)

x3

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [69]:
# torch.div()

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])

x1/5

tensor([[0.2000, 0.4000, 0.6000],
        [0.8000, 1.0000, 1.2000]])

### 2) pow, exp, log

In [74]:
# torch.pow(input,exponent)

x1 = torch.rand(3,4)

print(x1)
print(torch.pow(x1,2),"\n",x1**2)

tensor([[0.9270, 0.6997, 0.4527, 0.0064],
        [0.1234, 0.8673, 0.2865, 0.7553],
        [0.1044, 0.8684, 0.4367, 0.9106]])
tensor([[0.8593, 0.4895, 0.2050, 0.0000],
        [0.0152, 0.7522, 0.0821, 0.5704],
        [0.0109, 0.7540, 0.1907, 0.8292]]) 
 tensor([[0.8593, 0.4895, 0.2050, 0.0000],
        [0.0152, 0.7522, 0.0821, 0.5704],
        [0.0109, 0.7540, 0.1907, 0.8292]])


In [76]:
# torch.exp(tensor,out=None)

x1 = torch.rand(3,4)

print(x1)
print(torch.exp(x1))

tensor([[0.6662, 0.9783, 0.9775, 0.3907],
        [0.0661, 0.1779, 0.8077, 0.9035],
        [0.6897, 0.5909, 0.2927, 0.8435]])
tensor([[1.9469, 2.6600, 2.6579, 1.4780],
        [1.0684, 1.1947, 2.2428, 2.4682],
        [1.9930, 1.8055, 1.3400, 2.3244]])


In [77]:
# torch.log(input,out=None)

x1 = torch.rand(3,4)

print(x1)
print(torch.log(x1))

tensor([[0.2953, 0.4920, 0.6473, 0.9745],
        [0.3756, 0.9168, 0.3854, 0.1833],
        [0.0537, 0.8418, 0.7700, 0.0641]])
tensor([[-1.2197, -0.7093, -0.4349, -0.0258],
        [-0.9793, -0.0869, -0.9535, -1.6968],
        [-2.9246, -0.1722, -0.2614, -2.7475]])


In [78]:
# torch.mm(matrix1, matrix2)

x1 = torch.rand(3,4)
x2 = torch.rand(4,5)

torch.mm(x1,x2)

tensor([[1.4617, 1.3338, 0.6461, 0.5249, 1.1572],
        [1.5020, 1.3841, 0.8555, 0.7055, 1.5158],
        [1.0398, 0.7409, 0.4515, 0.4343, 0.8520]])

In [80]:
# torch.bmm(batch_matrix1, batch_matrix2)

x1 = torch.rand(10,3,4)
x2 = torch.rand(10,4,5)

torch.bmm(x1,x2).size()

torch.Size([10, 3, 5])

![img](https://github.com/shwksl101/Pytorch-A-to-Z/blob/master/img/innerproduct.PNG?raw=true)

In [85]:
# torch.dot(tensor1, tensor2)

torch.dot(torch.tensor([2,3]), torch.tensor([2,1]))

tensor(7)

In [88]:
# torch.t(matrix)
# tranpose

x1 = torch.rand(3,4)
print(x1.size(), x1.t().size())

# torch.transpose(input,dim0,dim1)

x1 = torch.rand(10,3,4)
x1.size(), torch.transpose(x1,1,2).size(), x1.transpose(1,2).size()

torch.Size([3, 4]) torch.Size([4, 3])


(torch.Size([10, 3, 4]), torch.Size([10, 4, 3]), torch.Size([10, 4, 3]))

In [91]:
# torch.eig(a,eigenvectors=Flase)
# eigen_value, eigen_vector

x1 = torch.rand(2,2)

print(x1,"\n",torch.eig(x1,True))

tensor([[0.3529, 0.5674],
        [0.9198, 0.8337]]) 
 (tensor([[-0.1681,  0.0000],
        [ 1.3546,  0.0000]]), tensor([[-0.7366, -0.4928],
        [ 0.6763, -0.8701]]))


### 3) view, item

In [53]:
# view()

x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) # -1의 경우 다른 차원들로 유추합니다. 이 경우에는 2로 유추합니다.
print(x.size())
print(y.size(),y)
print(z.size(),z)

torch.Size([4, 4])
torch.Size([16]) tensor([-0.1907,  1.4426,  0.8507,  1.6509, -1.6703, -0.6967,  0.6388, -0.1706,
        -0.4393,  3.7354,  0.3510,  0.9974, -0.0576, -0.6605, -1.7391,  0.5670])
torch.Size([2, 8]) tensor([[-0.1907,  1.4426,  0.8507,  1.6509, -1.6703, -0.6967,  0.6388, -0.1706],
        [-0.4393,  3.7354,  0.3510,  0.9974, -0.0576, -0.6605, -1.7391,  0.5670]])


In [57]:
# item()

x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0873])
1.0872668027877808


- 더 많은 연산은 다음의 링크에서 참고하세요 https://pytorch.org/docs/stable/torch.html

## 3. Tensor to Numpy, Numpy to Tensor

In [63]:
import numpy as np

In [60]:
a = torch.ones(5) # 1로 채워진 텐서를 생성합니다.
print(a)

tensor([1., 1., 1., 1., 1.])


In [61]:
# tensor.numpy()

b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [65]:
# torch.from_numpy(ndarray)

a = np.ones(5) #a와 b는 연동됩니다.
b = torch.from_numpy(a)

np.add(a,1,out=a)

print(a)
print(b) #chartensor를 제외한 모든 tensor는 numpy로의 변환을 지원합니다.

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## 4. Tensor on GPU

In [97]:
x= torch.FloatTensor([[1,2,3],[4,5,6]])

if torch.cuda.is_available():
    x_cuda = x.cuda()
else:
    x_cuda = x.cpu()
    
print(x_cuda)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [67]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu",torch.double)) #.to 기능을 tensor를 GPU로 연산할 수 있습니다

## 5. Indexing, Slicing, Joining

### 1) Indexing

In [105]:
# tensor.index_select(input,dim,index)

x = torch.rand(4,3)
out = torch.index_select(x,0,torch.LongTensor([0,3]))
# index는 꼭 Longtensor로 입력해야 합니다.

print(x, "\n", out)

tensor([[0.8311, 0.1818, 0.7193],
        [0.7232, 0.8519, 0.9920],
        [0.5484, 0.3168, 0.7273],
        [0.8554, 0.5796, 0.1729]]) 
 tensor([[0.8311, 0.1818, 0.7193],
        [0.8554, 0.5796, 0.1729]])


In [106]:
print(x)
print(x[:,0])
print(x[0,:])
print(x[0:2,0:2])

tensor([[0.8311, 0.1818, 0.7193],
        [0.7232, 0.8519, 0.9920],
        [0.5484, 0.3168, 0.7273],
        [0.8554, 0.5796, 0.1729]])
tensor([0.8311, 0.7232, 0.5484, 0.8554])
tensor([0.8311, 0.1818, 0.7193])
tensor([[0.8311, 0.1818],
        [0.7232, 0.8519]])


In [109]:
# torch.masked_select(input,mask)
# 1로 표시한 텐서만 고릅니다.

x = torch.randn(2,3)
mask = torch.ByteTensor([[0,0,1],[0,1,0]])
out = torch.masked_select(x,mask)

print(x,"\n", mask, "\n" ,out)

tensor([[-1.0903, -1.0116, -0.7674],
        [ 1.0127, -0.4559,  0.5633]]) 
 tensor([[0, 0, 1],
        [0, 1, 0]], dtype=torch.uint8) 
 tensor([-0.7674, -0.4559])


### 2) Joining

In [112]:
# torch.cat(seq, dim=0)
# dim을 기준으로 tensor를 합칩니다.
# dim = 0은 행, dim = 1은 열 기준입니다.

x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
y = torch.FloatTensor([[7,8,9],
                       [10,11,12]])
z1 = torch.cat([x,y],dim = 0)
z2 = torch.cat([x,y],dim = 1)

print(x)
print(y)
print(z1)
print(z2)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]])


In [116]:
# torch.stack(sequence,dim=0)
# dim을 기준으로 쌓습니다.

x = torch.FloatTensor([1,2,3])
x_stack = torch.stack([x,x],dim=0)
x_stack2 = torch.stack([x,x],dim=1)

print(x_stack,"\n",x_stack2)

tensor([[1., 2., 3.],
        [1., 2., 3.]]) 
 tensor([[1., 1.],
        [2., 2.],
        [3., 3.]])


### 3) Slicing

In [122]:
# torch.chunk(tensor, chunks, dim=0)
# tensor를 chunk 단위로 쪼갭니다.

x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
y = torch.FloatTensor([[7,8,9],
                       [10,11,12]])
z1 = torch.cat([x,y],dim = 0)

x_1, x_2 = torch.chunk(z1,2,dim=0)
y_1, y_2, y_3 = torch.chunk(z1,3,dim=1)

print(z1)
print(x_1)
print(x_2)
print(y_1)
print(y_2)
print(y_3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.],
        [ 4.],
        [ 7.],
        [10.]])
tensor([[ 2.],
        [ 5.],
        [ 8.],
        [11.]])
tensor([[ 3.],
        [ 6.],
        [ 9.],
        [12.]])


In [128]:
# torch.splot(tensor,splot_size,dim=0)

x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
y = torch.FloatTensor([[7,8,9],
                       [10,11,12]])
z1 = torch.cat([x,y],dim = 0)

x1,x2 = torch.split(z1,2,dim=0)
y1 = torch.split(z1,2,dim=1)

print(x1)
print(x2)
print(y1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
(tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]]), tensor([[ 3.],
        [ 6.],
        [ 9.],
        [12.]]))


### 4) squeezing

In [130]:
# torch.squeez(input, dim=None)
# 1짜리 차원을 줄입니다.

x1 = torch.FloatTensor(10,1,3,1,4)
x2 = torch.squeeze(x1)

x1.size(), x2.size()

(torch.Size([10, 1, 3, 1, 4]), torch.Size([10, 3, 4]))

In [131]:
# torch.unsqueeze(input,dim=None)
# 1짜리 차원을 더합니다.

x1 = torch.FloatTensor(10,3,4)
x2 = torch.unsqueeze(x1,dim=0)

x.size(), x2.size()

(torch.Size([2, 3]), torch.Size([1, 10, 3, 4]))

## 6. Initialization

In [133]:
import torch.nn.init as init

x1 = init.uniform_(torch.FloatTensor(3,4),a=0,b=9) 
x2 = init.normal_(torch.FloatTensor(3,4),std=0.2)
x3 = init.constant_(torch.FloatTensor(3,4),3.1415)

x1,x2,x3

(tensor([[1.0948, 5.2341, 7.3144, 3.9653],
         [1.7959, 1.4752, 6.9669, 4.4430],
         [4.3531, 1.3461, 8.8319, 6.9616]]),
 tensor([[ 0.1977, -0.0273, -0.3114,  0.2082],
         [-0.2204, -0.1628,  0.1662, -0.0214],
         [ 0.1363,  0.0342, -0.2627, -0.1452]]),
 tensor([[3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415]]))