# Autograd: 자동 미분

## Autograd Package

- Autograd 패키지는 tensor의 모든 연산에 자동 미분을 제공합니다. 이는 define-by-run의 프레임워크로 코드를 어떻게 작성하느냐에 따라 역전파가 정의된다는 뜻입니다. 역전파는 학습과정의 매 단계마다 달라집니다.

- .requires_grad 속성을 True로 설정하면 해당 tensor의 모든 연산을 추적합니다. 계산이 완료된 후 .backward()를 호출해 gradient를 자동으로 계산할 수 있습니다. 이 tensor의 gradient는 .grad에 누적됩니다.

- 연산 기록을 추적하는 것을 멈추기 위해 코드 블럭을 with torch.no_grad():로 감쌀 수 있습니다. gradient는 필요 없지만 requires_grad=True가 설정되어 학습 가능한 Parameter(매개변수)를 갖는 모델을 평가할 때 유용합니다.

In [18]:
import torch

In [19]:
x = torch.ones(2,2,requires_grad=True) #tensor를 생성하고 requires_grad=True로 연산을 기록합니다.
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [20]:
y = x+2 #gradient function이 자동으로 포함됩니다.
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [21]:
z = y*y*3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [22]:
a = torch.randn(2,2)
a = ((a*3)/(a-1)) 
print(a.requires_grad)
print(a.grad_fn) # 사용자가 만든 텐서의 grad_fn은 none입니다.
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn) #requires_grad_(True)로 지정하고 연산하면 이렇게 grad_fn가 생깁니다.

False
None
True


### Gradient

In [23]:
print(out) # out = 3(x+2)*2
out.backward()

tensor(27., grad_fn=<MeanBackward1>)


In [24]:
print(x)
print(x.grad) # d(out)/dx 를 출력합니다.

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [35]:
x = torch.randn(3,requires_grad=True)

y=x*2

while y.data.norm() < 1000:
    
    #data.norm()은 점들 사이의 유클리디안 거리를 나타냅니다
    #torch.sqrt(torch.sum(torch.pow(y, 2)))
    
    y = y*2
    
    print(y,y.data.norm())

tensor([-0.8602, -2.7999,  1.4120], grad_fn=<MulBackward>) tensor(3.2517)
tensor([-1.7205, -5.5999,  2.8239], grad_fn=<MulBackward>) tensor(6.5033)
tensor([ -3.4409, -11.1997,   5.6478], grad_fn=<MulBackward>) tensor(13.0066)
tensor([ -6.8818, -22.3995,  11.2956], grad_fn=<MulBackward>) tensor(26.0132)
tensor([-13.7636, -44.7989,  22.5913], grad_fn=<MulBackward>) tensor(52.0264)
tensor([-27.5272, -89.5979,  45.1826], grad_fn=<MulBackward>) tensor(104.0529)
tensor([ -55.0545, -179.1958,   90.3652], grad_fn=<MulBackward>) tensor(208.1057)
tensor([-110.1090, -358.3915,  180.7303], grad_fn=<MulBackward>) tensor(416.2114)
tensor([-220.2180, -716.7831,  361.4607], grad_fn=<MulBackward>) tensor(832.4229)
tensor([ -440.4359, -1433.5662,   722.9214], grad_fn=<MulBackward>) tensor(1664.8457)


In [36]:
gradients = torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
print(y)
y.backward(gradients)
print(x.grad) # d(y)/d(x) 를 출력합니다

tensor([ -440.4359, -1433.5662,   722.9214], grad_fn=<MulBackward>)
tensor([ 204.8000, 2048.0000,    0.2048])


In [40]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad) #tensor들의 연산 기록 추적을 막을 수 있습니다.
     
print((x**2).requires_grad)

True
True
False
True


- autograd package에 대한 더 자세한 정보는 다음의 링크를 참고하세요. https://pytorch.org/docs/stable/torch.html