## Why should we use Pytorch?
 
 - It's easy to develope deep learning models
 - paradigm tensorflow - define and run vs pytorch - define by run
 - opensource
 - easy to learn
 - more intuitive than tensorflow
 - can use GPU
 - easy to install

# Pytorch Packages

 - torch
 - torch.autograd
 - torch.nn
 - torch.optim
 - torch.multiprocessing
 - torch.utils
 - torch.legact

In [3]:
from __future__ import print_function
import torch

## torch package

In [4]:
x = torch.empty(5,3) #원하는 차원의 빈 텐서를 생성합니다.
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [6]:
x = torch.empty(5,7, dtype=torch.float) #이런식으로 dtype을 정해줄 수 있습니다.
print(x)
print(x.size())

tensor([[5.7858e-39, 8.4490e-39, 5.3266e-39, 7.8061e-39, 9.2755e-39, 1.0561e-38,
         1.0653e-38],
        [1.0561e-38, 8.4490e-39, 1.0102e-38, 9.0919e-39, 1.0102e-38, 8.9082e-39,
         8.4489e-39],
        [9.6429e-39, 8.4490e-39, 9.6429e-39, 9.2755e-39, 1.0286e-38, 9.0919e-39,
         8.9082e-39],
        [9.2755e-39, 8.4490e-39, 1.0010e-38, 8.4490e-39, 1.0837e-38, 1.0102e-38,
         9.9184e-39],
        [1.0194e-38, 8.4490e-39, 1.0010e-38, 1.0561e-38, 1.0469e-38, 8.9082e-39,
         4.2246e-39]])
torch.Size([5, 7])


In [9]:
x = torch.rand(5,3) #0~1 사이의 연속균등분포에서 값을 뽑아 텐서를 생성합니다.
print(x)

tensor([[0.6665, 0.4622, 0.2684],
        [0.5254, 0.4430, 0.5951],
        [0.4441, 0.1919, 0.6743],
        [0.0569, 0.5601, 0.1863],
        [0.7284, 0.4689, 0.8340]])


In [11]:
x = torch.zeros(5,3, dtype = torch.long) # dtype이 long이고 0으로 채워진 텐서를 생성합니다
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


- 데이터 타입의 종류

![dtype](https://github.com/shwksl101/Pytorch-A-to-Z/blob/master/img/dtype.PNG?raw=true)

In [8]:
x = torch.tensor([5.5,3]) #원하는 텐서를 바로 생성합니다.
print(x)

tensor([5.5000, 3.0000])


In [40]:
x = x.new_ones(5,3, dtype=torch.double) #5,3 차원의 새로운 텐서를 생성합니다.
print(x)

x = torch.randn_like(x,dtype=torch.float) # 같은 size에서 랜덤한 숫자로 채워진 텐서를 생성합니다.
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.5949,  0.3606, -0.0697],
        [-0.2124, -0.9243,  1.5786],
        [ 1.2222,  2.4934,  0.2329],
        [-0.6524, -0.3773,  0.1990],
        [ 0.1745, -0.0725, -1.3324]])


In [14]:
print(x.size()) # 행렬의 크기를 구합니다.

torch.Size([5, 3])


### Operations(연산)

In [27]:
torch.manual_seed(777) # 랜덤값 고정을 위해 사용되는 함수입니다.
y = torch.rand(5,3) # rand는 0~1사이의 값을 생성합니다. (uniform distribution) 
print(x+y)

tensor([[0.0819, 0.4911, 0.4033],
        [0.3859, 0.8813, 0.8811],
        [0.7242, 0.5033, 0.8249],
        [0.2634, 0.3112, 0.5948],
        [0.1092, 0.6213, 0.7350]])


In [29]:
print(torch.add(x,y)) #add 안의 텐서 값들을 더해줍니다.

tensor([[ 0.1662,  1.7615,  0.4850],
        [-1.7407,  0.7955, -0.0815],
        [ 0.9485, -0.9761,  1.0955],
        [-0.6268,  0.1395,  0.3799],
        [ 1.0049,  0.2290, -0.0202]])


In [41]:
result = torch.empty(5,3)
torch.add(x,y,out=result) #out option은 결과로 받을 텐서를 지정합니다.
print(result)

tensor([[ 0.9041,  0.6849,  0.9236],
        [ 0.0952, -0.7023,  2.2757],
        [ 1.6198,  2.6429,  0.6611],
        [-0.0710, -0.0013,  1.1837],
        [ 0.8743,  0.2068, -0.7936]])


In [43]:
x = torch.rand(1,5,3)
y = torch.rand(5,3)
torch.add(x,y) #차원이 다르더라도 안쪽 차원만 같으면 연산이 가능합니다.

tensor([[[0.6673, 0.6532, 0.8410],
         [0.9674, 1.7119, 0.4976],
         [0.9666, 1.5755, 0.9870],
         [0.8471, 0.3932, 1.5169],
         [0.2085, 1.1244, 1.7623]]])

In [45]:
x = torch.rand(5,3)
y.add_(x) # torch.add 말고 add_의 경우에는 이러한 연산 기능이 지원되지 않습니다. 따라서 먼저 x를 같은 차원으로 바꿔줍니다.
print(y)

tensor([[0.6340, 0.9185, 0.7175],
        [0.4609, 1.1804, 0.1689],
        [0.5956, 0.6734, 1.1183],
        [1.4676, 0.5494, 0.9229],
        [0.4351, 1.3508, 1.1279]])


In [47]:
print(x)
print(x[:,1]) #x 텐서의 2열을 불러옵니다. numpy 연산이 지원됩니다.

tensor([[0.5525, 0.3936, 0.5418],
        [0.0180, 0.2786, 0.0924],
        [0.2323, 0.0372, 0.9420],
        [0.6228, 0.3336, 0.1392],
        [0.3534, 0.4941, 0.3092]])
tensor([0.3936, 0.2786, 0.0372, 0.3336, 0.4941])


In [53]:
x = torch.randn(4,4) #randn의 경우 평균은 0, 표준편차는 1인 정규분포에서 값을 가져옵니다.
y = x.view(16)
z = x.view(-1,8) # -1의 경우 다른 차원들로 유추합니다. 이 경우에는 2로 유추합니다.
print(x.size())
print(y.size(),y)
print(z.size(),z)

torch.Size([4, 4])
torch.Size([16]) tensor([-0.1907,  1.4426,  0.8507,  1.6509, -1.6703, -0.6967,  0.6388, -0.1706,
        -0.4393,  3.7354,  0.3510,  0.9974, -0.0576, -0.6605, -1.7391,  0.5670])
torch.Size([2, 8]) tensor([[-0.1907,  1.4426,  0.8507,  1.6509, -1.6703, -0.6967,  0.6388, -0.1706],
        [-0.4393,  3.7354,  0.3510,  0.9974, -0.0576, -0.6605, -1.7391,  0.5670]])


In [57]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0873])
1.0872668027877808


- 더 많은 연산은 다음의 링크에서 참고하세요 https://pytorch.org/docs/stable/torch.html

## tensor to numpy (텐서를 넘파이로 변환하기)

In [60]:
a = torch.ones(5) # 1로 채워진 텐서를 생성합니다.
print(a)

tensor([1., 1., 1., 1., 1.])


In [61]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [62]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Numpy to tensor (넘파이 배열을 텐서로 변환하기)

In [63]:
import numpy as np

In [65]:
a = np.ones(5) #a와 b는 연동됩니다.
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b) #chartensor를 제외한 모든 tensor는 numpy로의 변환을 지원합니다.

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [67]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu",torch.double)) #.to 기능을 tensor를 GPU로 연산할 수 있습니다