## Practice - Backpropagation

In [1]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import torch.nn.functional as F
import torch.optim as optim

In [2]:
x = Variable(torch.Tensor([-2.0]),  requires_grad=True)
y = Variable(torch.Tensor([5.0]),  requires_grad=True)
z = Variable(torch.Tensor([-4.0]),  requires_grad=True)

q =  x+y
f = q*z

In [3]:
print(x)
print(y)
print(z)

tensor([-2.], requires_grad=True)
tensor([5.], requires_grad=True)
tensor([-4.], requires_grad=True)


In [4]:
print(q)
print(f)

tensor([3.], grad_fn=<ThAddBackward>)
tensor([-12.], grad_fn=<ThMulBackward>)


In [5]:
f.backward(retain_graph=True) #class로 하면 retain_graph=True 옵션을 안넣어도 됩니다. 차후에 다루겠습니다.

In [6]:
print(f.grad_fn)
print(q.grad_fn)

In [7]:
print(x.grad)
print(y.grad)
print(z.grad)

tensor([-4.])
tensor([-4.])
tensor([3.])


## TODO - Backpropagation

<img src="https://drive.google.com/uc?id=1Jvlk56B36HPyihMRACOxUFm7FwUTVL3v">

In [12]:
# 위의 directed acyclic graph를 구현해보겠습니다.

w0 = Variable(torch.Tensor([2.0]),  requires_grad=True)
x0 = Variable(torch.Tensor([-1.0]),  requires_grad=True)
w1 = Variable(torch.Tensor([-3.0]),  requires_grad=True)
x1 = Variable(torch.Tensor([-2.0]),  requires_grad=True)
w2 = Variable(torch.Tensor([-3.0]),  requires_grad=True)

q1 =  w0*x0
q2 = w1*x1
f1 = q1+q2
s = f1+w2

out = torch.sigmoid(s)
print(out)
out.backward(retain_graph=True)

tensor([0.7311], grad_fn=<SigmoidBackward>)


In [13]:
print(w0.grad)
print(x0.grad)
print(w1.grad)
print(x1.grad)
print(w2.grad)

tensor([-0.1966])
tensor([0.3932])
tensor([-0.3932])
tensor([-0.5898])
tensor([0.1966])


## Practice - Weight Update

In [15]:
w0 = Variable(torch.Tensor([2.0]), requires_grad=True)
x0 = Variable(torch.Tensor([-1.0]), requires_grad=True)
w1 = Variable(torch.Tensor([-3.0]), requires_grad=True)
x1 = Variable(torch.Tensor([-2.0]), requires_grad=True)
w2 = Variable(torch.Tensor([-3.0]), requires_grad=True)

q1 = w0*x0
q2 = w1*x1

r = q1 + q2
s = r + w2

out = torch.sigmoid(s)
print("=====================")
print("First Prediction")
print(out)

target = torch.Tensor([1.0])
optimizer = optim.SGD([w0, w1, w2], lr=0.1)
criterion = nn.MSELoss()
print("=====================")
print("Original Weight")
print(w0)
print(w1)
print(w2)


loss = criterion(out, target)
loss.backward()

print("=====================")
print("Gradient")

print(w0.grad)
print(w1.grad)
print(w2.grad)

optimizer.step() #weight update !

print("=====================")
print("Updated Weight") # w_new = w_origin - (learning_rate * gradient)

print(w0) # w0_new = w0(=2.0) - (0.1 * 0.1058) = 1.9894
print(w1) # w1_new = w1(=-3.0) - (0.1 * 0.2115) = -3.0212
print(w2) # w2_new = w2(=-3.0) - (0.1 * 0.1058) = -2.9894

q1 = w0*x0
q2 = w1*x1

r = q1 + q2
s = r + w2

out = torch.sigmoid(s)
print("=====================")
print("Second Prediction")

print(out)

First Prediction
tensor([0.7311], grad_fn=<SigmoidBackward>)
Original Weight
tensor([2.], requires_grad=True)
tensor([-3.], requires_grad=True)
tensor([-3.], requires_grad=True)
Gradient
tensor([0.1058])
tensor([0.2115])
tensor([-0.1058])
Updated Weight
tensor([1.9894], requires_grad=True)
tensor([-3.0212], requires_grad=True)
tensor([-2.9894], requires_grad=True)
Second Prediction
tensor([0.7433], grad_fn=<SigmoidBackward>)
