# Framework Comparison
    - Numpy vs Tensorflow vs Pytorch
    - output = x * y + z

In [1]:
import numpy as np
from datetime import datetime

start = datetime.now()

np.random.seed(0)

N,D = 3,4

x = np.random.randn(N,D)
y = np.random.randn(N,D)
z = np.random.randn(N,D)

a = x*y
b = a+z
c = np.sum(b)

grad_c = 1.0
grad_b = grad_c * np.ones((N,D))
grad_a = grad_b.copy()
grad_z = grad_b.copy()
grad_y = grad_a * y
grad_x = grad_a * x

print(grad_x)
print(grad_y)
print(grad_z)
print(datetime.now()-start)

[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]]
[[ 0.76103773  0.12167502  0.44386323  0.33367433]
 [ 1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
0:00:00.004463


In [4]:
import tensorflow as tf
import numpy as np
from datetime import datetime

start = datetime.now()

with tf.device('cpu'):
    
    x = tf.placeholder(tf.float32)
    y = tf.placeholder(tf.float32)
    z = tf.placeholder(tf.float32)
    
    a = x*y
    b = a+z
    c = tf.reduce_sum(b)
    
grad_x, grad_y, grad_z = tf.gradients(c,[x,y,z])

with tf.Session() as sess:
    values = {
        x: np.random.randn(N,D),
        y: np.random.randn(N,D),
        z: np.random.randn(N,D)
    }
    out = sess.run([c,grad_x,grad_y,grad_z],feed_dict=values)
    c_val, grad_x_val, grad_y_val, grad_z_val = out
    
print(grad_x_val)
print(grad_y_val)
print(grad_z_val)
print(datetime.now()-start)

[[ 0.37642553 -1.0994008   0.2982382   1.3263859 ]
 [-0.69456786 -0.14963454 -0.43515354  1.8492638 ]
 [ 0.67229474  0.40746182 -0.76991606  0.5392492 ]]
[[ 1.922942    1.4805148   1.867559    0.90604466]
 [-0.86122566  1.9100649  -0.26800337  0.8024564 ]
 [ 0.947252   -0.15501009  0.61407936  0.9222067 ]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
0:00:00.096217


In [11]:
import torch
from torch.autograd import Variable
from datetime import datetime
start = datetime.now()

N,D=3,4

x = Variable(torch.randn(N,D),requires_grad=True)
y = Variable(torch.randn(N,D),requires_grad=True)
z = Variable(torch.randn(N,D),requires_grad=True)

if torch.cuda.is_available():
    x_ = x.cuda()
    y_ = y.cuda()
    z_ = z.cuda()

a = x_*y_
b = a+z_
c = torch.sum(b)

c.backward()

print(x.grad)
print(y.grad)
print(z.grad)
print(datetime.now()-start)

SyntaxError: invalid syntax (<ipython-input-11-22f51608d628>, line 21)