# Framework Comparison
    - Numpy vs Tensorflow vs Pytorch
    - output = x * y + z

In [1]:
import numpy as np
from datetime import datetime

start = datetime.now()

np.random.seed(0)

N,D = 3,4

x = np.random.randn(N,D)
y = np.random.randn(N,D)
z = np.random.randn(N,D)

a = x*y
b = a+z
c = np.sum(b)

grad_c = 1.0
grad_b = grad_c * np.ones((N,D))
grad_a = grad_b.copy()
grad_z = grad_b.copy()
grad_y = grad_a * y
grad_x = grad_a * x

print(grad_x)
print(grad_y)
print(grad_z)
print(datetime.now()-start)

[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]]
[[ 0.76103773  0.12167502  0.44386323  0.33367433]
 [ 1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
0:00:00.002977


In [5]:
import tensorflow as tf
import numpy as np
from datetime import datetime

start = datetime.now()

with tf.device('cpu'):
    
    x = tf.placeholder(tf.float32)
    y = tf.placeholder(tf.float32)
    z = tf.placeholder(tf.float32)
    
    a = x*y
    b = a+z
    c = tf.reduce_sum(b)
    
grad_x, grad_y, grad_z = tf.gradients(c,[x,y,z])

with tf.Session() as sess:
    values = {
        x: np.random.randn(N,D),
        y: np.random.randn(N,D),
        z: np.random.randn(N,D)
    }
    out = sess.run([c,grad_x,grad_y,grad_z],feed_dict=values)
    c_val, grad_x_val, grad_y_val, grad_z_val = out
    
print(grad_x_val)
print(grad_y_val)
print(grad_z_val)
print(datetime.now()-start)

[[ 1.4882522   1.8958892   1.1787796  -0.17992483]
 [-1.0707526   1.0544517  -0.40317693  1.222445  ]
 [ 0.20827498  0.97663903  0.3563664   0.7065732 ]]
[[ 1.1394007  -1.2348258   0.40234163 -0.6848101 ]
 [-0.87079716 -0.5788497  -0.31155252  0.05616534]
 [-1.1651498   0.9008265   0.46566245 -1.5362437 ]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
0:00:00.071919


In [4]:
import torch
from datetime import datetime
start = datetime.now()

N,D=3,4

x = torch.randn(N,D,requires_grad=True)
y = torch.randn(N,D,requires_grad=True)
z = torch.randn(N,D,requires_grad=True)

if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = z.cuda()

a = x*y
b = a+z
c = torch.sum(b)

c.backward()

print(x.grad)
print(y.grad)
print(z.grad)
print(datetime.now()-start)

tensor([[ 0.8803,  0.7955, -0.3067,  0.1629],
        [-0.9482,  0.0540,  0.6933,  1.0126],
        [ 0.4330,  0.6478, -0.6824,  0.1981]])
tensor([[ 0.4886, -1.2655, -0.3224, -1.0496],
        [-2.0527,  1.2421, -1.5813, -1.0075],
        [-1.2879, -1.4438,  0.7893,  0.9215]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
0:00:00.005985
